### ISSUE TITLE
grok free documentation

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.dexterity#128]
Documentation still uses grok example. this is no longer best practice and confuses newbiees a lot. 

All grok need to be removed and exchanged with classic zcml based registrations.

**Comment by paregorios** [comment]
+1

**Comment by thet** [comment]
Can we remove the docs/grok directory? The grok-free docs in docs/ seem mostly as they could completely replace the docs in the grok subdirectory.

cc @plone/framework-team @plone/documentation-team

**Comment by svx** [comment]
@thet 
sure but unfortunately this will not be enough to solve it, but certainly a good begin !

One of the biggest 'issues' is still that grok (and grok examples) is mentioned in various docs of repositories which are 'embedded' in the docs. 

For example https://github.com/plone/plone.app.dexterity/issues/162.

What we may/should do during a sprint ?

- remove docs/grok
- scan docs where we have to adjust parts because of this removal
- search through all 'external' docs we include and remove/update/fix the the docs part about grok

We tried that already at various sprints, usually people are not "motivated" to work on this.

We had only *one* sprint, the last one at 4d aka superlecker, where @kcleong removed a lot of grok and updated docs and examples.

**Thanks again, for doing this !**

I will spare all of us now the speech about the importance of docs :)

So yeah it would be super awesome, but we need people who are willing to help.

:)

**Comment by jensens** [comment]
meanwhile, all was ungroked.
